### ISSUE TITLE
Reminders not working on my own (private) repo

### ISSUE THREAD

**Issue by smileBeda** [agrc/reminder-action#175]
I have added the yml file with these contents to my `.github/workflows/main.yml` file in the private repo
```
name: Issue Management Workflow

 on:
   schedule:
     - cron: '0 9 * * *' # This line sets a schedule for the action to run. This example would run every day at 9:00 AM.

 jobs:
   reminder:
     runs-on: ubuntu-latest
     steps:
       - name: Issue Reminder
         uses: agrc/reminder-action@v1.0.11
```

 I then added a comment to an issue `/remind me of this tomorrow` which did not work. It did not work.

I tried a similar one on the very repo here (#9) and it worked.

I then copied the issues comment yml and scheduled yml files from this very repo to my own, tried the /remind me of this in 5 seconds there... did not work.

What am I doing wrong?
