### ISSUE TITLE
What exactly is supposed to happen?!

### ISSUE THREAD

**Issue by smileBeda** [agrc/reminder-action#179]
I seem confused as of what the `reminder` command actually is suppose to do.

1. I set a reminder following the syntax `/reminder (what) (when)`
2. This adds the `reminder` tag and also a follow up comment by bot ==> OK
3. Nothing ever happens after that ==> NOK

I would expect to actually be _reminded_ about the issue, at the given time, by email, or whatever - IPoAC or else is fine with me too. But a reminder should remind me!

Do I misunderstand the tool? If this just adds the tag and comment, it is not very useful, I can do that myself.

**Comment by smileBeda** [comment]
I have two workflows:
- `scheduled.yml`
```
name: Scheduled Events

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  reminder:
    name: Notify
    runs-on: ubuntu-latest

    steps:
    - name: ⚠️ Notify
      uses: agrc/reminder-action@v1
```
- `issue_comment.yml`
```
name: Issue Comment Events

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    name: Check for reminder
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Check for reminder
        uses: agrc/create-reminder-action@v1
```

So I think yes?

And I can see the actions running, and succeeding.

Again.. what exactly is supposed to happen?
1. I comment with `/reminder (what) (when)`
2. It creates a new comment with contents like `@username set a reminder for 6/27/2024`
3. ... ? Nothing happens ever, other than the tag `reminder` gets removed, as I noted, once the date expires, but I get no email, no new comment, zero nada zilch.

Can you let me know what should happen?
